name: build Next.js web application
on: push
jobs:
  build-project:
    name: build project
    runs-on: ubuntu-latest
    steps:
    - name: Checkour code
      uses: actions/checkout@v3
    - name: Install NPM dependencies
      run: npm install
    - name: Build project assets
      run: npm run build